# This is a basic workflow that is manually triggered

name: Parking System FE build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: 
      - "FE/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pnpm/action-setup@v4.2.0
      with:
        version: latest
        standalone: true
    - uses: actions/checkout@v5.0.0
    - name: Instal package
      working-directory: './FE'
      run: pnpm install
    - name: Build package
      working-directory: './FE'
      run: pnpm build
    - name: auth service account 2
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: install gcloud
      uses: 'google-github-actions/setup-gcloud@v3'
    - name: clean
      run: gcloud storage rm --recursive --continue-on-error gs://parking-service-ui/**
    - name: upload to Cloud Storage
      working-directory: './FE/dist/parking-system-ui/browser'
      run: gcloud storage cp --recursive ./ gs://parking-service-ui
